workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 20
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk
    scripts:
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
