workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 20
    scripts:
      - name: Build APK
        script: |
          gradle assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
