workflows:
  build-android:
    name: Build APK
    environment:
      sdk: 31
    scripts:
      - name: Give execute permission to gradlew
        script: chmod +x ./gradlew
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
