workflows:
  android-app:
    name: Build Android APK
    max_build_duration: 60
    environment: {}
    scripts:
      - name: Set execute permission for gradlew
        script: chmod +x ./gradlew
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
