workflows:
  build-android:
    name: Build Android APK
    environment:
      android: true
    scripts:
      - name: Build Debug APK
        script: |
          cd App
          gradle assembleDebug
    artifacts:
      - App/app/build/outputs/**/*.apk
