workflows:
  build-android:
    name: Build Android APK
    instance_type: linux_x2
    max_build_duration: 20
    environment:
      vars:
        JAVA_HOME: /opt/android/java/openjdk
    scripts:
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
