workflows:
  build-android:
    name: Build Android APK
    environment:
      sdk: 33
      java: 17
    scripts:
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
